version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'orderSystem'
      MYSQL_USER: 'orderSystem'
      MYSQL_PASSWORD: 'challenge'
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - spring-mysql-network
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/orderSystem?useSSL=false
      ACCESS_TOKEN_ENV_VAR: epvKsEPPXJvrBzvqAKgluEoxkCYWQ
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-mysql-network
networks:
  spring-mysql-network:
